### ISSUE TITLE
Does not pull any data from the 2.0 agent

### ISSUE THREAD

**Issue by skibum1869** [TrakHound/TrakHound-Community#43]
When using a 2.0 agent, TrakHound will not pull data as it just comes up as unavailable. I have tried all of the Mazak agents up to 2.0, where the issues occur. 

![image](https://user-images.githubusercontent.com/15605269/184910877-27c206e4-7e15-4bfc-8675-32e108d599d2.png)

**Comment by skibum1869** [comment]
![image](https://user-images.githubusercontent.com/15605269/184912927-fc029a8c-d41f-4a96-950c-5c53bdcbe247.png)

**Comment by PatrickRitchie** [comment]
I just published a [v1.5.9](https://github.com/TrakHound/TrakHound-Community/releases/tag/v1.5.9) release that should fix this issue. Looks like there was a bug with the Url and it was defaulting to the full Devices document. I think this was causing it to read the Agent Device which is why it was missing information.

Let me know if you find anything else.

Thanks,
-Patrick

**Comment by skibum1869** [comment]
Looks like it fixed the issue
